//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace p2pWeb.p2pService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="p2pService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/loginUser", ReplyAction="http://tempuri.org/IService1/loginUserResponse")]
        string loginUser(string xmlCOntent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/loginUser", ReplyAction="http://tempuri.org/IService1/loginUserResponse")]
        System.Threading.Tasks.Task<string> loginUserAsync(string xmlCOntent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/registerUser", ReplyAction="http://tempuri.org/IService1/registerUserResponse")]
        string registerUser(p2p.Entities.User.UserRegisterDTO urd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/registerUser", ReplyAction="http://tempuri.org/IService1/registerUserResponse")]
        System.Threading.Tasks.Task<string> registerUserAsync(p2p.Entities.User.UserRegisterDTO urd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/signoutUser", ReplyAction="http://tempuri.org/IService1/signoutUserResponse")]
        string signoutUser(string xmlContent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/signoutUser", ReplyAction="http://tempuri.org/IService1/signoutUserResponse")]
        System.Threading.Tasks.Task<string> signoutUserAsync(string xmlContent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/enableDisableUser", ReplyAction="http://tempuri.org/IService1/enableDisableUserResponse")]
        string enableDisableUser(p2p.Entities.User.UserInfoDTO uid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/enableDisableUser", ReplyAction="http://tempuri.org/IService1/enableDisableUserResponse")]
        System.Threading.Tasks.Task<string> enableDisableUserAsync(p2p.Entities.User.UserInfoDTO uid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getUsersList", ReplyAction="http://tempuri.org/IService1/getUsersListResponse")]
        p2p.Entities.User.UsersListDTO getUsersList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getUsersList", ReplyAction="http://tempuri.org/IService1/getUsersListResponse")]
        System.Threading.Tasks.Task<p2p.Entities.User.UsersListDTO> getUsersListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteUser", ReplyAction="http://tempuri.org/IService1/deleteUserResponse")]
        string deleteUser(p2p.Entities.User.UserInfoDTO uid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteUser", ReplyAction="http://tempuri.org/IService1/deleteUserResponse")]
        System.Threading.Tasks.Task<string> deleteUserAsync(p2p.Entities.User.UserInfoDTO uid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/updateUser", ReplyAction="http://tempuri.org/IService1/updateUserResponse")]
        string updateUser(p2p.Entities.User.UserInfoDTO uid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/updateUser", ReplyAction="http://tempuri.org/IService1/updateUserResponse")]
        System.Threading.Tasks.Task<string> updateUserAsync(p2p.Entities.User.UserInfoDTO uid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/searchFiles", ReplyAction="http://tempuri.org/IService1/searchFilesResponse")]
        p2p.Entities.File.FileSearchResultDTO searchFiles(string xmlContent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/searchFiles", ReplyAction="http://tempuri.org/IService1/searchFilesResponse")]
        System.Threading.Tasks.Task<p2p.Entities.File.FileSearchResultDTO> searchFilesAsync(string xmlContent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getFilesList", ReplyAction="http://tempuri.org/IService1/getFilesListResponse")]
        p2p.Entities.File.FilesListDTO getFilesList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getFilesList", ReplyAction="http://tempuri.org/IService1/getFilesListResponse")]
        System.Threading.Tasks.Task<p2p.Entities.File.FilesListDTO> getFilesListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/downloadRequest", ReplyAction="http://tempuri.org/IService1/downloadRequestResponse")]
        p2p.Entities.File.FileResponseDTO downloadRequest(p2p.Entities.File.FileRequestDTO request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/downloadRequest", ReplyAction="http://tempuri.org/IService1/downloadRequestResponse")]
        System.Threading.Tasks.Task<p2p.Entities.File.FileResponseDTO> downloadRequestAsync(p2p.Entities.File.FileRequestDTO request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getStatistics", ReplyAction="http://tempuri.org/IService1/getStatisticsResponse")]
        p2p.Entities.Info.StatisticsDTO getStatistics();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getStatistics", ReplyAction="http://tempuri.org/IService1/getStatisticsResponse")]
        System.Threading.Tasks.Task<p2p.Entities.Info.StatisticsDTO> getStatisticsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : p2pWeb.p2pService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<p2pWeb.p2pService.IService1>, p2pWeb.p2pService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string loginUser(string xmlCOntent) {
            return base.Channel.loginUser(xmlCOntent);
        }
        
        public System.Threading.Tasks.Task<string> loginUserAsync(string xmlCOntent) {
            return base.Channel.loginUserAsync(xmlCOntent);
        }
        
        public string registerUser(p2p.Entities.User.UserRegisterDTO urd) {
            return base.Channel.registerUser(urd);
        }
        
        public System.Threading.Tasks.Task<string> registerUserAsync(p2p.Entities.User.UserRegisterDTO urd) {
            return base.Channel.registerUserAsync(urd);
        }
        
        public string signoutUser(string xmlContent) {
            return base.Channel.signoutUser(xmlContent);
        }
        
        public System.Threading.Tasks.Task<string> signoutUserAsync(string xmlContent) {
            return base.Channel.signoutUserAsync(xmlContent);
        }
        
        public string enableDisableUser(p2p.Entities.User.UserInfoDTO uid) {
            return base.Channel.enableDisableUser(uid);
        }
        
        public System.Threading.Tasks.Task<string> enableDisableUserAsync(p2p.Entities.User.UserInfoDTO uid) {
            return base.Channel.enableDisableUserAsync(uid);
        }
        
        public p2p.Entities.User.UsersListDTO getUsersList() {
            return base.Channel.getUsersList();
        }
        
        public System.Threading.Tasks.Task<p2p.Entities.User.UsersListDTO> getUsersListAsync() {
            return base.Channel.getUsersListAsync();
        }
        
        public string deleteUser(p2p.Entities.User.UserInfoDTO uid) {
            return base.Channel.deleteUser(uid);
        }
        
        public System.Threading.Tasks.Task<string> deleteUserAsync(p2p.Entities.User.UserInfoDTO uid) {
            return base.Channel.deleteUserAsync(uid);
        }
        
        public string updateUser(p2p.Entities.User.UserInfoDTO uid) {
            return base.Channel.updateUser(uid);
        }
        
        public System.Threading.Tasks.Task<string> updateUserAsync(p2p.Entities.User.UserInfoDTO uid) {
            return base.Channel.updateUserAsync(uid);
        }
        
        public p2p.Entities.File.FileSearchResultDTO searchFiles(string xmlContent) {
            return base.Channel.searchFiles(xmlContent);
        }
        
        public System.Threading.Tasks.Task<p2p.Entities.File.FileSearchResultDTO> searchFilesAsync(string xmlContent) {
            return base.Channel.searchFilesAsync(xmlContent);
        }
        
        public p2p.Entities.File.FilesListDTO getFilesList() {
            return base.Channel.getFilesList();
        }
        
        public System.Threading.Tasks.Task<p2p.Entities.File.FilesListDTO> getFilesListAsync() {
            return base.Channel.getFilesListAsync();
        }
        
        public p2p.Entities.File.FileResponseDTO downloadRequest(p2p.Entities.File.FileRequestDTO request) {
            return base.Channel.downloadRequest(request);
        }
        
        public System.Threading.Tasks.Task<p2p.Entities.File.FileResponseDTO> downloadRequestAsync(p2p.Entities.File.FileRequestDTO request) {
            return base.Channel.downloadRequestAsync(request);
        }
        
        public p2p.Entities.Info.StatisticsDTO getStatistics() {
            return base.Channel.getStatistics();
        }
        
        public System.Threading.Tasks.Task<p2p.Entities.Info.StatisticsDTO> getStatisticsAsync() {
            return base.Channel.getStatisticsAsync();
        }
    }
}
